### ISSUE TITLE
BoCA-1.1-alpha-20180306 does not compile on Linux Mint 18.3

### ISSUE THREAD

**Issue by wkremser** [enzo1982/BoCA#3]
This is the error i get trying to build the library:

make[3]: Entering directory '/home/wkremser/Projects/freac-universe/BoCa/BoCA-1.1-alpha-20180306/components/decoder/cdio'
g++ -fvisibility=hidden -DBOCA_COMPONENT_BUILD -DHAVE_OLD_PARANOIA_INCLUDE=1 -I/home/wkremser/Projects/freac-universe/BoCa/BoCA-1.1-alpha-20180306/components/decoder/cdio/../../../include -fPIC -pthread  -c cdio.cpp -o cdio.o
g++ -fvisibility=hidden -DBOCA_COMPONENT_BUILD -DHAVE_OLD_PARANOIA_INCLUDE=1 -I/home/wkremser/Projects/freac-universe/BoCa/BoCA-1.1-alpha-20180306/components/decoder/cdio/../../../include -fPIC -pthread  -c config.cpp -o config.o
g++ -fvisibility=hidden -DBOCA_COMPONENT_BUILD -DHAVE_OLD_PARANOIA_INCLUDE=1 -I/home/wkremser/Projects/freac-universe/BoCa/BoCA-1.1-alpha-20180306/components/decoder/cdio/../../../include -fPIC -pthread  -c info/cdinfo.cpp -o info/cdinfo.o
g++ -fvisibility=hidden -DBOCA_COMPONENT_BUILD -DHAVE_OLD_PARANOIA_INCLUDE=1 -I/home/wkremser/Projects/freac-universe/BoCa/BoCA-1.1-alpha-20180306/components/decoder/cdio/../../../include -fPIC -pthread  -c info/cdtext.cpp -o info/cdtext.o
info/cdtext.cpp: In member function ‘smooth::Int BoCA::CDText::ReadCDText(const smooth::String&)’:
info/cdtext.cpp:33:39: error: too few arguments to function ‘cdtext_t* cdio_get_cdtext(CdIo_t*, track_t)’
  cdtext_t *cdtext = cdio_get_cdtext(cd);
                                       ^
In file included from /usr/include/cdio/cdio.h:79:0,
                 from info/cdtext.cpp:15:
/usr/include/cdio/track.h:112:13: note: declared here
   cdtext_t *cdio_get_cdtext (CdIo_t *p_cdio, track_t i_track);
             ^
info/cdtext.cpp:40:45: error: ‘CDTEXT_FIELD_PERFORMER’ was not declared in this scope
   cdInfo.SetArtist(cdtext_get_const(cdtext, CDTEXT_FIELD_PERFORMER, 0));
                                             ^
info/cdtext.cpp:41:44: error: ‘CDTEXT_FIELD_TITLE’ was not declared in this scope
   cdInfo.SetTitle(cdtext_get_const(cdtext, CDTEXT_FIELD_TITLE, 0));
                                            ^
../../../Makefile-commands:88: recipe for target 'info/cdtext.o' failed
make[3]: *** [info/cdtext.o] Error 1
make[3]: Leaving directory '/home/wkremser/Projects/freac-universe/BoCa/BoCA-1.1-alpha-20180306/components/decoder/cdio'
Makefile:34: recipe for target 'cdio' failed
make[2]: *** [cdio] Error 2
make[2]: Leaving directory '/home/wkremser/Projects/freac-universe/BoCa/BoCA-1.1-alpha-20180306/components/decoder'
Makefile:14: recipe for target 'decoder' failed
make[1]: *** [decoder] Error 2
make[1]: Leaving directory '/home/wkremser/Projects/freac-universe/BoCa/BoCA-1.1-alpha-20180306/components'
Makefile:8: recipe for target 'all' failed
make: *** [all] Error 2

These are the cdio packages installed on my system:
libcdio-cdda-dev:amd64                        0.83-4.2ubuntu1 
libcdio-cdda1:amd64                           0.83-4.2ubuntu1
libcdio-dev:amd64                             0.83-4.2ubuntu1
libcdio-paranoia-dev:amd64                    0.83-4.2ubuntu1
libcdio-paranoia1:amd64                       0.83-4.2ubuntu1
libcdio13:amd64                               0.83-4.2ubuntu1

**Comment by wkremser** [comment]
Ah ok, danke für die Infos ..

Ich hab versucht freac selber zu kompilieren, weil die alpha bei mir immer wieder abstürzt beim laden von cds. Ich verwende ein Setup mit 4 CD Laufwerken zum rippen und ein intel nuc system mit Linux Mint 18.3.

Bevor ich Fehlermeldungen zum Thema Abstürze schicke, wollte ich versuchen ob eine selbstkompilierte Version die Fehler behebt.

Falls ich doch die Stack Traces von den Abstürzen schicken soll, lassen Sie es mich bitte wissen.

LG
Wolfgang Kremser

**Comment by enzo1982** [comment]
Ja, ein Stack-Trace wäre nett. Evtl. kann ich damit die Ursache für die Abstürze ausfindig machen.

Die Datei cdtext.cpp ist jetzt aktualisiert, um ältere Versionen von libcdio zu unterstützten. Damit sollte das Kompilieren klappen:

https://github.com/enzo1982/BoCA/raw/master/components/decoder/cdio/info/cdtext.cpp

**Comment by wkremser** [comment]
Thx .. compilation succeeded now.

i will open a new issue in fre:ac with the stack traces soon.
